version: 0.0
os: linux
files:
  - source: /
    destination: /var/app
hooks:
  ApplicationStart:
    - location: /var/app/scripts/start.sh
      runas: ec2-user
permissions:
  - object: ///deployment-archive/scripts/start.sh
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
      - file