version: 0.0
os: linux
files:
  - source: /
    destination: /var/app
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      runas: ec2-user
permissions:
  - object: ./var/app/scripts
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file