version: 0.0
os: linux
files:
  - source: /
    destination: /var/app
permissions:
  - object: /var/app/scripts/change_permission.sh
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
hooks:
  ApplicationStart:
    - location: scripts/change_permission.sh
      runas: ec2-user