version: 0.0
os: linux
files:
  - source: /
    destination: /var/app
permissions:
  - object: scripts/start.sh
    # pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: ec2-user