version: '3'
services:
  mysql:
    image: mysql:5.7
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == ip-172-31-43-71.ap-northeast-1.compute.internal]
    environment:
        MYSQL_DATABASE: menuDB
        MYSQL_USER: ken3pei
        MYSQL_PASSWORD: pass
        MYSQL_ROOT_PASSWORD: rootpass
    ports:
        - "3306:3306"
    volumes:
        - mysql-data:/var/lib/mysql
volumes:
    mysql-data: