version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
        MYSQL_DATABASE: menuDB
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
        - "3306:3306"
    volumes:
        - mysql-data:/var/lib/mysql
volumes:
    mysql-data: